config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :articles do
    resources :comments
  end

  root 'articles#home'

  get '/home', to: 'articles#home'
  get '/contributors', to: 'users#index'
  get '/search_results', to: 'articles#search_results'

  get '/sign_up', to: 'users#new'

  get '/my_profile', to: 'users#my_profile'
  get '/edit_profile', to: 'users#edit'
  post '/edit_profile', to: 'users#edit'

  get '/log_in', to: 'sessions#new'
  post 'log_in', to: 'sessions#create'
  
  get '/log_out', to: 'sessions#destroy'

  get '/new_article', to: 'articles#new'

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments

  validates :title, length: {
    minimum: 5,
    maximum: 20,
    too_short: "Please lengthen title",
    too_long: "Please shorten title" }
  validates :body, length: {
    minimum: 50,
    maximum: 5000,
    too_short: "Please write a little bit more (at least 50 characters)",
    too_long: "Please keep article below 5000 characters" }

  extend FriendlyId
  friendly_id :title, use: :slugged

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :article

  validates :body, length: {
    minimum: 2,
    maximum: 30,
    too_short: "Please write a little more",
    too_long: "Please keep comment under 30 characters" }

end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  has_many :articles
  has_many :comments

  validates :username, uniqueness: true, length: { in: 4..12 }, on: :create
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness: true, on: :create
  validates :password, confirmation: true, length: { in: 6..20 }, on: :create
  validates :password_confirmation, presence: true, on: :create

  mount_uploader :picture, PictureUploader

  extend FriendlyId
  friendly_id :username, use: :slugged

  def admin?
    self.admin == true
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user 

  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id] 
  end
    
  def require_user 
    redirect_to '/login' unless current_user 
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def home
    @articles = Article.limit(3).order("created_at DESC")
  end

  def index
    @articles = Article.all.order("created_at DESC")
  end

  def show
    @article = Article.friendly.find(params[:id])
    @comments = @article.comments.order("created_at DESC")
  end

  def search_results
    if params[:q]
      search_term = params[:q]
      if Rails.env.production?
        @articles = Article.where("title ilike :search or body ilike :search", {search: "%#{search_term}%"})
      else
        @articles = Article.where("title like :search or body like :search", {search: "%#{search_term}%"})
      end
    end
  end

  def new
    if session[:user_id]
      @article = Article.new
    else
      redirect_to '/', alert: 'Please sign up or log in.'
    end
  end

  def create
    @article = Article.new(article_params)
    @article.user_id = current_user.id
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article has been created.' }
      else
        format.html { render 'new' }
      end
    end
  end

  def edit
    @article = Article.friendly.find(params[:id])
    if session[:user_id] && (current_user.admin? || current_user.id == @article.user_id)
      @article = Article.friendly.find(params[:id])
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  def update
    @article = Article.friendly.find(params[:id])
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article has been updated.' }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    @article = Article.friendly.find(params[:id])
    if session[:user_id] && (current_user.admin? || current_user.id == @article.user_id)
      @article = Article.friendly.find(params[:id])
      @article.destroy
      redirect_to articles_path
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  def article_params
    params.require(:article).permit(:title, :body, :user_id)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.friendly.find(params[:article_id])
    if session[:user_id] && current_user
      @comment = @article.comments.new(comment_params)
      @comment.user = current_user
      @comment.save
      redirect_to article_path(@article)
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if session[:user_id] && (current_user.admin? || current_user == @comment.user)
      article = @comment.article
      @comment.destroy
      redirect_to article
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    @user = User.find_by_email(params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to '/', notice: 'Successfully logged in.'
    else
      redirect_to '/log_in', alert: 'Please make sure you enter your correct email and password.'
    end
  end
  
  def destroy 
    session[:user_id] = nil
    reset_session   # Added to protect from session fixation
    redirect_to '/', notice: 'Successfully logged out.'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 def index
    @users = User.all
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def my_profile
    @user = current_user
    @articles = @user.articles
  end

  def new
    @user = User.new
  end

  def create 
    @user = User.new(user_params)
    if @user.save 
      session[:user_id] = @user.id
      UserMailer.welcome(@user).deliver_now
      redirect_to '/', notice: 'Sign up was successful.'
    else 
      render 'new'
    end 
  end

  def edit
    if session[:user_id] && current_user
      @user = current_user
      @user.picture = params[:picture]
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  def update
    @user = current_user
    @user.picture = params[:picture]
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'Profile has been updated' }
      else
        format.html { render 'edit' }
      end
    end
  end

  def destroy
    if session[:user_id] && current_user
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User deleted' }
      end
    else
      redirect_to '/', alert: 'You are not allowed to do this.'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :username, :home_country, :current_country, :languages, :description, :password, :password_confirmation, :picture, :remove_picture, :remote_picture_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/user_registrations_helper.rb
module UserRegistrationsHelper
end

app/views/articles/_comments.html.erb
<div class="comments">
  <h3 class="comment-headings">What others have said</h3>
  <% @comments.each do |comment| %>
    <hr>
    <p><%= comment.user.first_name %>, <i><%= comment.created_at.time.to_formatted_s(:long) %></i>
      <% if current_user && (current_user.admin? || current_user == comment.user) %>
        <%= link_to ('<span class="glyphicon glyphicon-remove"></span>').html_safe, article_comment_path(@article, comment), method: :delete, data: { confirm: 'Are you sure?' }, id: "comment-delete" %>
      <% end %>
    </p>
    <p><%= comment.body %></p>
  <% end %>
</div>

app/views/articles/_new_article.html.erb
<% if @article.errors.any? %>
  <div id="error-explanation">
    <h4>Sorry, there is/are <%= pluralize(@article.errors.count, "error") %>:</h4>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@article) do |f| %>
  <div class="field">
    <%= f.label :title, "Your title" %><br>
    <%= f.text_field :title, autofocus: true, class: "form-control" %>
  </div>
  <br>
  <div class="field">
    <%= f.label :body, "Your article" %><br>
    <%= f.text_area :body, class: "form-control", rows: 20, maxlength: 5000, id: "text-area-noresize" %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Submit", class: "btn btn-custom" %>
  </div>
<% end %>

app/views/articles/_new_comment.html.erb
<% if @article.errors.any? %>
  <div id="error-explanation">
    <h4>Sorry, there is/are <%= pluralize(@article.errors.count, "error") %>:</h4>
    <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if current_user %>
  <hr>
  <h4 class="comment-headings">Leave a comment</h4>
  <%= form_for([@article, @article.comments.build]) do |f| %>
    <p>
      <%= f.label :body, "Comment", class: "comment-headings" %><br>
      <%= f.text_area :body, autofocus: true, class: "form-control", rows: 2, maxlength: 100, id: "text-area-noresize" %>
    </p> 
    <p>
      <%= f.submit "Submit", class: "btn btn-navigate" %>
    </p>
  <% end %>
<% end %>

app/views/articles/edit.html.erb
<div class="general-content">
  <h1>Edit article</h1>

  <%= render 'new_article' %>

</div>

app/views/articles/home.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="jumbotron-content">
      <h1>Welcome Abroad</h1>
      <h2>A blog dedicated to living abroad</h2>
      <br>
      <p>
        <%= link_to("Read Articles", '/articles', class: "btn btn-custom btn-lg") %>
        <% if current_user %>
          <%= link_to("Write an Article", '/new_article', class: "btn btn-custom btn-lg") %>
        <% else %>
          <%= link_to("Sign Up", '/sign_up', class: "btn btn-custom btn-lg") %>
        <% end %>
      </p>
    </div>
  </div><!-- end of .container -->
</div>

<div class="container">
  <div class="welcome-intro">
    <% if current_user %>
      <h2>Welcome back, <i><%= current_user.first_name %>!</i></h2>
      <hr>
    <% end %>

    <h2>Share your experiences in another country</h2>
    <p>For all those living, studying, or working in a country other than their own.<br>
    Read articles by others, write articles of your own, comment on what others have said!</p>
  </div>

  <div class="welcome-articles">
    <h3>Here are some recent articles</h3>
      <% @articles.each do |article| %>
        <hr>
        <h4><%= link_to article.title, article %></h4>
        <p>By <%= article.user.first_name %>, <%= article.created_at.time.to_formatted_s(:long) %></p>
      <% end %>
  </div>

</div><!-- end of .container -->

<div class="container">
  <div class="row">
    <div class="read-write-share">
      <div class="col-xs-4">
        <%= image_tag("icons/read.png", class: "img-responsive") %>
        <p>Read</p>
      </div>
      <div class="col-xs-4">
        <%= image_tag("icons/write.png", class: "img-responsive") %>
        <p>Write</p>
      </div>
      <div class="col-xs-4">
        <%= image_tag("icons/share.png", class: "img-responsive") %>
        <p>Share</p>
      </div>
    </div>
  </div><!-- end of .row -->
</div><!-- end of .container -->

<div class="extra-space"></div>

app/views/articles/index.html.erb
<div class="general-content">

  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-xs-12 col-xs-offset-0">
      <h1>Here is a list of all articles</h1>
      <hr>
      <% @articles.each do |article| %>
        <h3><%= link_to article.title, article %></h3>
        <p>By <%= article.user.first_name %>, <%= article.created_at.time.to_formatted_s(:long) %></p>
        <hr>
      <% end %>
    </div>
  </div><!-- end of .row -->

</div>

<div class="extra-space"></div>

app/views/articles/new.html.erb
<div class="general-content">
  <h1>Write an article</h1>
  <h3>Share your thoughts and experiences</h3>
  <p>Please respect the guidelines for submissions: no bad language or anything that might be offensive. (Otherwise we'll have to remove it.)</p>

  <%= render 'new_article' %>
</div>

<div class="extra-space"></div>

app/views/articles/search_results.html.erb
<div class="general-content">
  <h1>Your Search</h1>

  <div class="container">
    <div class="row">
      <% if @articles.present? %>
        <h4>Here are the results of your search for "<%= params[:q] %>":</h4>
          <% @articles.each do |article| %>
            <div class="row">
              <div class="col-md-12">
                <%= link_to article.title, article %>
              </div>
            </div><!-- end of .row -->
          <% end %>
      <% else %>
        <h4>Sorry, there are no articles containing "<%= params[:q] %>".</h4>
      <% end %>
    </div><!-- end of .row -->
  </div><!-- end of .container -->

</div>

<div class="extra-space"></div>

app/views/articles/show.html.erb
<div class="general-content">
  <h3><%= @article.title %></h3>
  <p>By <%= @article.user.first_name %>, <%= @article.created_at.time.to_formatted_s(:long) %></p>
  <br>
  <p><%= @article.body %></p>
    <% if current_user && (current_user.admin? || current_user == @article.user) %>
      <%= link_to 'Edit', edit_article_path(@article), class: "btn btn-navigate" %>
      <%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-navigate" %>
    <% end %>

  <%= render 'new_comment' %>
  <hr>
  <%= render 'comments' %>
  <hr>
  <%= link_to 'Back', articles_path, class: "btn btn-navigate" %>

</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="footer-content">
      <p><a href="#">Terms &amp; Conditions</a> | <a href="#">Impressum</a><br>
      Copyright 2016, Abroad.</p>
    </div>

    <div class="socia-media-links">
      <p>Connect on</p>

      <a class="btn btn-social-icon btn-facebook">
        <span class="fa fa-facebook"></span>
      </a>

      <a class="btn btn-social-icon btn-twitter">
        <span class="fa fa-twitter"></span>
      </a>

      <a class="btn btn-social-icon btn-instagram">
        <span class="fa fa-instagram"></span>
      </a>
    </div>

  </div><!-- end of .container -->
</footer>

app/views/layouts/_head.html.erb
<head>
  <title>Abroad</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.0.0/bootstrap-social.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://use.fontawesome.com/981382a342.js"></script>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Christian McTighe">
  <%= csrf_meta_tags %>
</head>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to("Abroad", '/home', class: "navbar-brand") %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav">
        <li></li>
        <li><%= link_to("Articles", '/articles') %><span class="sr-only">(current)</span></li>
        <li><a href="/contributors">Contributors</a></li>
      </ul>
      <div class="navbar-form navbar-left">
        <%= form_tag("/search_results", method: "get", class: "search-form") do %>
          <%= text_field_tag :q, nil, class: "form-control", placeholder: "Enter a keyword" %>
          <%= submit_tag("Search", class: "btn btn-custom") %>
        <% end %>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to("New Article", '/new_article') %></li>
          <li><%= link_to("My Profile", '/my_profile') %></li>
          <li><%= link_to("Logout", '/log_out') %></li>
        <% else %>
          <li><%= link_to "Sign Up", '/sign_up' %></li>
          <li><%= link_to("Log In", '/log_in') %></li>
        <% end %>
      </ul>
    </div><!-- .navbar-collapse -->

  </div><!-- .container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>

  <body>

    <%= render 'layouts/nav' %>

    <% if notice %>
      <p class="alert alert-warning"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>

  </body>

</html>

app/views/users/_edit_profile.html.erb
<% if @user.errors.any? %>
  <div id="error-explanation">
    <h4>Sorry, there is/are <%= pluralize(@user.errors.count, "error") %>:</h4>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="container">
  <%= form_for(@user) do |f| %>

  <div class="row">

    <div class="col-md-4">
      <% if @user.picture.present? %>
        <%= image_tag @user.picture.url, class: "img-responsive" %>
        <label><%= f.check_box :remove_picture %> Remove picture</label>
      <% else %>
        <div id="profile-picture"></div>
        <br>
        <div class="field">
          <%= f.label "Upload picture" %>
          <%= f.file_field :picture %>
        </div>
      <% end %>
    </div><!-- end of .col-md-4 -->

    <div class="col-md-6">
      <div class="field">
        <%= f.text_field :username, autofocus: true, placeholder: "User Name", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :home_country, placeholder: "Home Country", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :current_country, placeholder: "Curent Country", class: "form-control" %>
      </div>

      <div class="field">
        <%= f.text_field :languages, placeholder: "Languages Spoken", class: "form-control" %>
      </div>
      <br>
      <p><i>Tell us a little about yourself.</i></p>
      <div class="field">
        <%= f.text_area :description, class: "form-control", rows: 10, maxlength: 400, id: "text-area-noresize" %>
      </div>
      <br>
      <div class="actions">
        <%= f.submit "Update", class: "btn btn-custom" %>
      </div>
    </div><!-- end of .col-md-6 -->

  </div><!-- end of .row -->

  <% end %><!-- end of form_for -->

</div><!-- end of .container -->

app/views/users/_sign_up.html.erb
<% if @user.errors.any? %>
  <div id="error-explanation">
    <h4>Sorry, there is/are <%= pluralize(@user.errors.count, "error") %>:</h4>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="user-form">
  <%= form_for(@user) do |f| %>

    <div class="input-group input-group-sm">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-user"></span>
      </span>
      <div class="field">
        <%= f.text_field :first_name, autofocus: true, placeholder: "First Name", class: "form-control" %>
      </div>
    </div>

    <div class="input-group input-group-sm">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-user"></span>
      </span>
      <div class="field">
        <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
      </div>
    </div>

    <div class="input-group input-group-sm">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-user"></span>
      </span>
      <div class="field">
        <%= f.text_field :username, placeholder: "User Name", class: "form-control" %>
      </div>
    </div>

    <div class="input-group input-group-sm">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-envelope"></span>
      </span>
      <div class="field">
        <%= f.email_field :email, placeholder: "Email", class: "form-control" %>
      </div>
    </div>

    <div class="input-group input-group-sm">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-lock"></span>
      </span>
      <div class="field">
        <%= f.password_field :password, autocomplete: "off", placeholder: "Password", class: "form-control" %>
      </div>
    </div>
    <div class="input-group input-group-sm">
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-lock"></span>
      </span>
      <div class="field">
        <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", placeholder: "Retype your Password" %>
      </div>
    </div>
    <br>
    <%= f.submit "Create an account", class: "btn btn-custom" %>

  <% end %><!-- end of form_for -->

</div>

app/views/users/edit.html.erb
<div class="general-content">
  <h1>My Profile</h1>
  <h3>Edit your profile here.</h3>
  <br>

  <div class="user-form">
    
    <%= render 'edit_profile' %>

    <%= link_to 'Back', '/my_profile', class: "btn btn-navigate" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="general-content">
  <h1>Here are all of our contributors</h1>
  <br>

  <div class="container-fluid">
    <div class="row">
      <% @users.each do |user| %>
          <div class="col-md-4 col-sm-6 col-xs-12">
            <hr>
            <div class="col-xs-6">
              <%= image_tag(user.picture.thumb.url, class: "img-responsive") if user.picture.thumb.present? %>
            </div>
            <div class="col-xs-6">
              <p><b>Username:</b> <%= user.username %></p>
              <p><b>Name:</b> <%= user.first_name %></p>
              <p><b>Home Country:</b> <%= user.home_country %></p>
              <p><b>Current Country:</b> <%= user.current_country %></p>
              <%= link_to 'See full bio', user, class: "btn btn-navigate" %>
              <br>
            </div>
          </div><!-- end of .col-md-4 -->
      <% end %>
    </div><!-- end of .row -->
    <hr>
  </div><!-- end of .container-fluid -->

</div>

<div class="extra-space"></div>

app/views/users/my_profile.html.erb
<div class="general-content">
  <h2>My Profile</h2>
  <br>
  <div class="container">
    <div class="row">

      <div class="col-md-4">
        <% if @user.picture.present? %>
          <%= image_tag @user.picture.url, class: "img-responsive" %>
        <% else %>
          <div id="profile-picture"></div>
        <% end %>
      </div>

      <div class="col-md-8">
        <p><b>Username</b>
        <%= @user.username %></p>
        <p><b>First Name</b>
        <%= @user.first_name %></p>
        <p><b>Home Country</b>
        <%= @user.home_country %></p>
        <p><b>Current Country</b>
        <%= @user.current_country %></p>
        <p><b>Languages</b>
        <%= @user.languages %></p>
        <p><b>Description</b>
        <%= @user.description %></p>
        <br>
        <%= link_to 'Edit Profile', '/edit_profile', class: "btn btn-navigate" %>
      </div>

      <div class="col-md-12">
        <hr>
        <h4>Articles written</h4>

        <% if @articles %>
          <% @articles.each do |article| %>
            <p><%= link_to article.title, article %></p>
          <% end %>
        <% end %>
        <hr>
      </div>

    </div><!-- end of .row -->
  </div><!-- end of .container -->

</div>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2 col-xs-12 col-xs-offset-0">
      <div class="content">

        <h1>Sign Up</h1>
        <%= render 'sign_up' %>

      </div>
    </div>
  </div>  
</div>

app/views/users/show.html.erb
<div class="container">
  <h2><%= @user.username %></h2>
  <br>
  <div class="row">

    <div class="col-md-4">
      <% if @user.picture.present? %>
        <%= image_tag @user.picture.url, class: "img-responsive" %>
      <% else %>
        <div id="profile-picture"></div>
      <% end %>
      <br>
    </div>

    <div class="col-md-4">
      <p><b>Username</b>
      <%= @user.username %></p>
      <p><b>First Name</b>
      <%= @user.first_name %></p>
      <p><b>Home Country</b>
      <%= @user.home_country %></p>
      <p><b>Current Country</b>
      <%= @user.current_country %></p>
      <p><b>Languages</b>
      <%= @user.languages %></p>
      <p><b>Description</b>
      <%= @user.description %></p>
    </div>

  </div><!-- end of .row -->
</div><!-- end of .container -->

<div class="extra-space"></div>